language: csharp
solution: RssFeedParser.sln
mono: none
dotnet: 2.0.0
dist: trusty
addons:
  sonarcloud:
    organization: "mhtsbt-github"
script:
 - chmod +x ./build.sh && ./build.sh
 - sonar-scanner
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: release